### ISSUE TITLE
UI changes - make cards responsive

### ISSUE THREAD

**Issue by pvgupta24** [pvgupta24/Youtube-Playlist#2]
In the home.html template, all playlists are shown as cards in rows.
> Make this responsive, to adjust according to screen width.

**Comment by ifedyukin** [comment]
@pvgupta24, @mishal23 can you add a description of the task?

**Comment by mishal23** [comment]
@ifedyukin Please check the updated issue.

**Comment by ifedyukin** [comment]
@mishal23 ok, assign me please. I fix that soon.

**Comment by mishal23** [comment]
@ifedyukin  Please try sending a PR within 24 hours.
And, please do include screenshots of the UI changes.
