### ISSUE TITLE
Make navbar responsive (UI changes)

### ISSUE THREAD

**Issue by pvgupta24** [pvgupta24/Youtube-Playlist#5]
> Navbar is not displayed properly on screens of different widths
> Content on right side of navbar is not being displayed on smaller screens.(mobile)
> Search bar animated width on click has few issues.

Fix and send a PR

**Comment by RakshithNM** [comment]
I would like to work on this

**Comment by RakshithNM** [comment]
The collapse class has display property set to none on it. I would presume that the right nav items should be centered on collapse to the next line on smaller viewports!
